- name: create user group
  group:
    name: "{{ user }}"
    state: present

- name: Create basic user
  user:
    name: "{{ user }}"
    state: present
    shell: /bin/bash
    group: "{{ user }}"
    home: "/home/{{ user }}"
